language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 DIET_TOOLS_DIR=/usr/bin
    - python: "3.4"
      env: TOXENV=py34 DIET_TOOLS_DIR=/usr/bin
    - python: "3.5"
      env: TOXENV=py35 DIET_TOOLS_DIR=/usr/bin
    - python: "pypy"
      env: TOXENV=pypy DIET_TOOLS_DIR=/usr/bin

sudo: false # Use container-based infrastructure
addons:
  apt:
    packages:
      - optipng

# command to install dependencies
install: 
  - pip install coveralls
  - pip install tox
# command to run tests
script: 
  tox
after_success:
  coveralls
